# Enable Colours
set -g default-terminal 'xterm-256color'
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

# Prefix Key
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Open new windows in current directory path
bind c new-window -c "#{pane_current_path}"

# Split Windows
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Reload Config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "󰑓 Config reloaded"

# Resize Panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

# Enable Mouse
set -g mouse on

# Scrollback
set -g history-limit 50000

# Enable Mouse Dragging
unbind -T copy-mode-vi MouseDragEnd1Pane

# Status Line Position
set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Keep the selection active after dragging with the mouse
unbind -T copy-mode-vi MouseDragEnd1Pane 
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-no-clear

# Themes
set -g @plugin "janoamaral/tokyo-night-tmux" # Installation
set -g @tokyo-night-tmux_theme storm    # storm | day | default to 'night'
set -g @tokyo-night-tmux_transparent 1  # 1 or 0
set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare
# Icon styles
set -g @tokyo-night-tmux_terminal_icon 
set -g @tokyo-night-tmux_active_terminal_icon 

# No extra spaces between icons
set -g @tokyo-night-tmux_window_tidy_icons 0


# To immediately kill a painel
bind-key & kill-window
bind-key x kill-pane

set -g @plugin 'catppuccin/tmux#v2.3.0' # See https://github.com/catppuccin/tmux/tags for additional tags
# ...alongside
set -g @plugin 'tmux-plugins/tpm'


set -g @catppuccin_flavor 'macchiato' # latte, frappe, macchiato or mocha

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line more pleasant.
set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '

# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 100

# provide clipboard
set -s set-clipboard on




































# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/.tmux/plugins/tpm/tpm'
